### ISSUE TITLE
Compile error: re.h and rem_fir.h missing

### ISSUE THREAD

**Issue by ttarhan** [alfredh/baresip-ios#1]
The following error is observed during the build:

CC      /Users/ttarhan/Development/OpenSource/baresip/build/armv7/librem/fir/fir.o
src/fir/fir.c:9:16: error: re.h: No such file or directory
src/fir/fir.c:10:21: error: rem_fir.h: No such file or directory

**Comment by DheerubhaiBansal** [comment]
When I am using $ sudo make install command in Ubuntu, I am getting this error
fatal error: re.h: No such file or directory.
I am using android studio.
