### ISSUE TITLE
iOS audio problems

### ISSUE THREAD

**Issue by jfont555** [alfredh/baresip-ios#17]
Hi all, i'm testing baresip to be the base of a voip service. I based my tests in something similar like this:
https://gist.github.com/ramki1979/6112198 

Basically i don't use ua_connect function because i need all the handlers of the call...
Wtih this setup i can establish a call but i can't hear any audio between two real devices, here is the console output:

stdio.so: No such file or directory
aucodec: PCMA/8000/1
aufilt: vumeter
auplay: coreaudio
ausrc: coreaudio

vidsrc: avcapture

[;m[31mmodule opengl.so: No such file or directory
[;mmedianat: stun
medianat: turn
medianat: ice

[;mPopulated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
registering <sip------@sip2sip.info>...
register reply: 200 OK
inviting <sip:-------@sip2sip.info>...
session progress: 100 Giving a try
session progress: 100 Trying
session progress: 100 Giving a try
SDP answer received
SDP peer address: 81.23.228.129:54272
SDP media format: PCMU/8000/1 (payload type: 0)
session established
register reply: 200 OK 

Thanks in advance, any help is welcome! :) @alfredh

**Comment by hyakus** [comment]
@jfont555 did you ever solve this issue? How did you get on with using baresip for iOS in general?

Thanks.

**Comment by jfont555** [comment]
@hyakus we switched to pjsip... Baresip seems a good option but requires a lot of time to get it working. 
Anyway if still interested, take a look in taresip, to get a fast working environment: https://github.com/miche-atucha/taresip

**Comment by hyakus** [comment]
@jfont555 thanks for getting back to me. Ended up getting sorted building the libraries locally actually and it turns out that my version of this problem was that I hadn't enabled the 'coreaudio' module under EXTRA_MODULES in the modules.mk file.

Essentially, I ended up building my own ObjC handler and passed it to baresip using uag_event_register() and ensuring that the library doesn't set up it's own call event handler over the top. 

It seems to work pretty well though I'm having a couple of issues I'm experiencing currently with regards to catching certain events with it that I'm looking into.

Glad you got yours sorted. It has been a mission with little to no documentation.

**Comment by samirmagnates** [comment]
> @jfont555 thanks for getting back to me. Ended up getting sorted building the libraries locally actually and it turns out that my version of this problem was that I hadn't enabled the 'coreaudio' module under EXTRA_MODULES in the modules.mk file.
> 
> Essentially, I ended up building my own ObjC handler and passed it to baresip using uag_event_register() and ensuring that the library doesn't set up it's own call event handler over the top.
> 
> It seems to work pretty well though I'm having a couple of issues I'm experiencing currently with regards to catching certain events with it that I'm looking into.
> 
> Glad you got yours sorted. It has been a mission with little to no documentation.

I have same issue, can't get Audio, and I tried with your solution, like
In modules.mk I have changed code

`
#ifneq ($(USE_COREAUDIO),)

MODULES   += coreaudio

#endif
`
 but now I am getting following error.
<a href="https://ibb.co/tKfM5r3"><img src="https://i.ibb.co/MSTDL09/Screenshot-2019-04-25-at-6-05-28-PM.png" alt="Screenshot-2019-04-25-at-6-05-28-PM" border="0" /></a>

Error is : 

> error: use of undeclared identifier 'AudioObjectPropertyAddress'
        AudioObjectPropertyAddress propertyAddress = {

Could you please help me for the same?

Thanks in advance...
