### ISSUE TITLE
dyld: Library not loaded: libre.dylib  Reason: image not found

### ISSUE THREAD

**Issue by AdilSoomro** [alfredh/baresip-ios#2]
I followed your guidelines and was able to make library. 

I draged the resulted armv7 folder to my project and added single line in AppDelegate's `didFinishLaunchingWithOptions` method..

```
/* Initialise System library */
int err = libre_init();
```

when I `command + click` on this method, it reveals the method in `...armv7/include/re/re_main.h` file. 

I'm able to compile it. but when I run it crashes and shows following debug info in logs

```
dyld: Library not loaded: libre.dylib
Referenced from: /var/mobile/Applications/C43EE39E-9DAA-4F4D-9EF9-4A41A8A5BAED/my.app/my
Reason: image not found
```

Here is screenshot of my project's Linked Framework and Libraries section.:

![Screen.png](https://f.cloud.github.com/assets/856233/3558/109419c4-42d4-11e2-935d-bebacfabfbd2.png)

Any insights to this problem will be much appreciated.

As I found [this](http://stackoverflow.com/a/12594805/593709) which said to make library optional didn't work out as when execution reaches on the above line of code, app crashes again.

**Comment by bhautik-ziniya** [comment]
> @johnnyfama Have you solved your problem.
> 
> I had also the same problem today and I have solved it.
> If anyone have the same problem, just reply here..

@ramki1979  I have also same issue when app lunch it crash

```
dyld: Library not loaded: libre.dylib
  Referenced from: /var/containers/Bundle/Application/5C6A4D3A-7821-423A-885B-3822C0BC78DB/BaresipDemo_ManualLib.app/BaresipDemo_ManualLib
  Reason: image not found
``` 
Can you please give the solution to resolve issue?

**Comment by bhautik-ziniya** [comment]
> Solved it, it needed few native frameworks to be added. Now my Framework and Libraries section looks like this:
> 
> ![Screen shot 2012-12-13 at 8 22 41 PM](https://camo.githubusercontent.com/73ffa3718204a4201197d7d3e9002951774392da/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3835363233332f31303930362f63376239643631342d343533382d313165322d386236612d6437323331386666333138372e706e67)
> 
> but it compiles for device only. _works for me_

Hi @AdilSoomro, 
I'm also getting the same error 

```
dyld: Library not loaded: libre.dylib
  Referenced from: /var/containers/Bundle/Application/5C6A4D3A-7821-423A-885B-3822C0BC78DB/BaresipDemo_ManualLib.app/BaresipDemo_ManualLib
  Reason: image not found
```

I have added all the framework you have mention in the screenshot, what other framework you have added to solve the problem? can you please mention all the framework? or any other solve to this problem?

**Comment by lilkid3** [comment]
Hi @bhautik-ziniya Have you solved the problem ?

> > Solved it, it needed few native frameworks to be added. Now my Framework and Libraries section looks like this:
> > ![Screen shot 2012-12-13 at 8 22 41 PM](https://camo.githubusercontent.com/73ffa3718204a4201197d7d3e9002951774392da/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3835363233332f31303930362f63376239643631342d343533382d313165322d386236612d6437323331386666333138372e706e67)
> > but it compiles for device only. _works for me_
> 
> Hi @AdilSoomro,
> I'm also getting the same error
> 
> ```
> dyld: Library not loaded: libre.dylib
>   Referenced from: /var/containers/Bundle/Application/5C6A4D3A-7821-423A-885B-3822C0BC78DB/BaresipDemo_ManualLib.app/BaresipDemo_ManualLib
>   Reason: image not found
> ```
> 
> I have added all the framework you have mention in the screenshot, what other framework you have added to solve the problem? can you please mention all the framework? or any other solve to this problem?
> 
> Here is screenshot of my project's Linked Framework and Libraries section:
> 
> ![image](https://user-images.githubusercontent.com/44424594/56038552-e2c6f500-5d4f-11e9-80db-17d42930cf25.png)

**Comment by AdilSoomro** [comment]
We moved from baresip to another sip stack. So really sorry if I don't reply to your questions as I'm really out of context of baresip.

**Comment by lilkid3** [comment]
> We moved from baresip to another sip stack. So really sorry if I don't reply to your questions as I'm really out of context of baresip.

Thank you for your response.
