### ISSUE TITLE
Can't get Audio.

### ISSUE THREAD

**Issue by samirmagnates** [alfredh/baresip-ios#21]
> @jfont555 thanks for getting back to me. Ended up getting sorted building the libraries locally actually and it turns out that my version of this problem was that I hadn't enabled the 'coreaudio' module under EXTRA_MODULES in the modules.mk file.
> 
> Essentially, I ended up building my own ObjC handler and passed it to baresip using uag_event_register() and ensuring that the library doesn't set up it's own call event handler over the top.
> 
> It seems to work pretty well though I'm having a couple of issues I'm experiencing currently with regards to catching certain events with it that I'm looking into.
> 
> Glad you got yours sorted. It has been a mission with little to no documentation.

I have same issue, can't get Audio, and I tried with your solution, like
In modules.mk I have changed code

```

#ifneq ($(USE_COREAUDIO),)

MODULES   += coreaudio

#endif

```
 but now I am getting following error.
<a href="https://ibb.co/tKfM5r3"><img src="https://i.ibb.co/MSTDL09/Screenshot-2019-04-25-at-6-05-28-PM.png" alt="Screenshot-2019-04-25-at-6-05-28-PM" border="0" /></a>

Error is : 

> error: use of undeclared identifier 'AudioObjectPropertyAddress'
        AudioObjectPropertyAddress propertyAddress = {

Could you please help me for the same?

If I uncomment the above code and run the command, all working fine there is no issue, but can't get audio in call.

Thanks in advance...

_Originally posted by @samirmagnates in https://github.com/alfredh/baresip-ios/issues/17#issuecomment-486660158_

**Comment by xyz-ios1** [comment]
@alfredh could you please guide me for the same issue, because without any comment you have closed the ticket.

**Comment by samirmagnates** [comment]
@alfredh could you please let me know why you close the ticket without any comment..... I need help for audio issue.
