### ISSUE TITLE
Error Code:43 Protocol not supported

### ISSUE THREAD

**Issue by AdilSoomro** [alfredh/baresip-ios#3]
I've been trying to solve this out.
I've been following [this open source project](http://tomeko.net/software/SIPclient/index.php) which is written c/c++, I was trying to replicate the login/registration on sip server part, but always getting 

`SIP register failed: Protocol not supported`

[This](https://gist.github.com/4328066) is the code which I've tried so far.

Any insight to this issue?

**Comment by shkumar18** [comment]
Hi @alfredh @chenlucu i have build  and complied the baresip in ubuntu and changed the code according to my requirement directly calling the faunction instaed of giving input from command line.
i have tried the video call but what i can see is that only i can see my self video and that too freezes.
could you pls suggest why this is happenning.
for video i have set video_mode on
err = ua_connect(f->a.ua, NULL, NULL, uri, NULL, VIDMODE_ON);

**Comment by samirmagnates** [comment]
> Okay, this issue got resolved, I was preferring ipv6, when doing `ua_init` so I put `NO` in the last argument, then it seemed to be working.
> 
> Now I'm stuck to another problem. which is that it is not calling any of the response handlers. It just keep displaying `Registering...`

in the baresip library, I checked the function has only 4 arguments and you passed five arguments.
`      int  ua_init(const char *software, bool udp, bool tcp, bool tls);`
I think either you are using another library or I am using another library... My library is baresip 0.6.5, could you please help me and let me know which library version you are using?
