### ISSUE TITLE
Guide or Xcode sample code to show how to integrate baresip libraries and iOS project

### ISSUE THREAD

**Issue by ivanlin** [alfredh/baresip-ios#9]
Hi, 

Is there any guide or Xcode sample code to show how to enable video and audio functions with this baresip libraries?

Thanks.

Ivan

**Comment by alfredh** [comment]
I dont have such guide at the moment.

contributions are welcome

**Comment by miche-atucha** [comment]
i started a cocoapod library: [taresip](https://github.com/miche-atucha/taresip) based on this repo, it work for me on the time i did it, but i have not updated it in a long time, just in case u want to look at it
